# Merging & Joining Data
---
Often, data is split across multiple tables or files. Pandas lets you combine them just like SQL — or even more flexibly!

In [2]:
import pandas as pd

In [3]:
employees = pd.DataFrame({
"EmpID": [1, 2, 3],
"Name": ["Alice", "Bob", "Charlie"],
"DeptID": [10, 20, 30]
})
departments = pd.DataFrame({
"DeptID": [10, 20, 40],
"DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

## Merge Like SQL: pd.merge()

In [11]:
pd.merge(employees, departments , on= "DeptID") # Inner Joint (By default)
# on means common column (IF there is only one common column then pandas automantically takes this )

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [17]:
pd.merge(employees, departments , on= "DeptID" , how= "right") # Right Joint using how=
# Takes all the column of right and common from left .. here right is departments cause it written in left

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [18]:
pd.merge(employees, departments , on= "DeptID" , how= "left") # Left Joint using how=

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [19]:
pd.merge(employees, departments , on= "DeptID" , how= "outer") # Outer Joint using how=

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

## Concatenating DataFrames
---
Use pd.concat() to stack datasets either vertically or horizontally.

In [20]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [21]:
df1

    Name
0  Alice
1    Bob

In [22]:
df2

      Name
0  Charlie
1    David

In [24]:
pd.concat([df1,df2]) # Vertical by default

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [25]:
pd.concat([df1,df2],axis=1) # Horizontal by using axis= 1

    Name     Name
0  Alice  Charlie
1    Bob    David