# Reading & Writing Files in Pandas
---
## CSV Files

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv") # Read CSV

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [9]:
df = df[df['IMDb']>7.0]
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [10]:
df.to_csv("data_updated.csv", index=False) #index= False means to remove the index (0,2,5,6,11) while writing

In [11]:
df1 = pd.read_excel("students_data.xlsx")

In [12]:
df1

    ID     Name  Age       City  Marks
0  101    Alice   25      Delhi     88
1  102      Bob   30     Mumbai     92
2  103  Charlie   22  Bangalore     81
3  104    David   28    Chennai     75
4  105      Eva   24     Jaipur     95

In [13]:
df1 = df1[df1['Marks']>80]
df1

    ID     Name  Age       City  Marks
0  101    Alice   25      Delhi     88
1  102      Bob   30     Mumbai     92
2  103  Charlie   22  Bangalore     81
4  105      Eva   24     Jaipur     95

### saving process is same as csv ***.to_excel***

## Multiple sheets ..

In [15]:
with pd.ExcelWriter("actor_students_data_merged.xlsx") as writer:
    df.to_excel(writer, sheet_name="Actors", index=False)
    df1.to_excel(writer, sheet_name="Students", index=False)